sudo: required
services:
  - docker

before_install:
  - docker build -t norothir/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run norothir/react-test npm test -- --coverage

after_success:
  - docker build -t norothir/multi-client ./client
  - docker build -t norothir/multi-nginx ./nginx 
  - docker build -t norothir/multi-server ./server
  - docker build -t norothir/multi-worker ./worker  
  # Login docker hub cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push norothir/multi-client 
  - docker push norothir/multi-nginx 
  - docker push norothir/multi-server
  - docker push norothir/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: mutka
  env: Mutka-env 
  bucket_name: elasticbeanstalk-us-west-2-653086257072
  bucket_path: docker-multi1
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY  